### ISSUE TITLE
Security exception: Cannot disable a protected package: com.amazon.device.software.ota

### ISSUE THREAD

**Issue by dbolser** [mrhaydendp/Fire-Tools#20]
## Describe the bug:

Set up USB Debugging and fired up Fire-Tools/ui.sh

Clicked Disable OTA -> OK, got the following msg:

```
Security exception: Cannot disable a protected package: com.amazon.device.software.ota

java.lang.SecurityException: Cannot disable a protected package: com.amazon.device.software.ota
	at com.android.server.pm.PackageManagerService.setEnabledSetting(PackageManagerService.java:21114)
	at com.android.server.pm.PackageManagerService.setApplicationEnabledSetting(PackageManagerService.java:21025)
	at com.android.server.pm.PackageManagerShellCommand.runSetEnabledSetting(PackageManagerShellCommand.java:1617)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:208)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21668)
	at android.os.Binder.shellCommand(Binder.java:634)
	at android.os.Binder.onTransact(Binder.java:532)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2796)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3975)
	at android.os.Binder.execTransact(Binder.java:731)
Failed to Disable OTA Updates
Device Connected
```

## To Reproduce:

As above.

## Expected behavior:
Shouldn't throw an error at the very least.

I'm guessing more recent versions of Fire OS have introduced new ways to cripple tools like yours...

Can we root?

## Platform:
- Linux
- Latest Version of Script?
-- IDK... I guess? You should add a VERSION file ;-)

## Device:
- Model Fire HD 8 (8th Gen)
- Version  [e.g. Fire OS 7.3.2.4]

## Additional context:

I've just done a factory reset to see if I can get an earlier OS, but the above is what I have. There are updates pending (which is why I wanted to turn on OTA ;-)

Several other things are 'not quite right', e.g. errors when installing Gapps, errors of the above nature during debloat, etc.

I can make a full report if it's usefull

**Comment by dbolser** [comment]
```
...
Failed to Disable: com.amazon.alexa.multimodal.gemini
...
Failed to Disable: com.amazon.tcomm.client
Failed to Disable: com.amazon.tcomm
Failed to Disable: com.amazon.client.metrics
Failed to Disable: com.amazon.platform
Failed to Disable: com.amazon.device.sync.sdk.internal
Failed to Disable: com.amazon.sync.service
Failed to Disable: com.amazon.device.sync
Failed to Disable: com.amazon.minerva.client.api
Failed to Disable: com.amazon.device.messaging
Failed to Disable: com.amazon.device.metrics
Failed to Disable: com.fireos.usagestats.proxy
Failed to Disable: com.fireos.arcus.proxy
Failed to Disable: com.amazon.sync.service
Failed to Disable: com.amazon.kindle.otter.oobe
Failed to Disable: com.amazon.diode
Failed to Disable: com.amazon.csapp
Failed to Disable: com.amazon.legalsettings
Failed to Disable: com.amazon.identity.auth.device.authorization
Failed to Disable: com.amazon.pm
Failed to Disable: com.amazon.kindle.kso
Failed to Disable: com.amazon.securitysyncclient
Failed to Disable: com.amazon.whisperlink.core.android
...
Disabling Telemetry & Resetting Advertising ID
Success
Disabling Location
Blocking Ads With Adguard DNS
Disabling Lockscreen Ads
Disabling Search on Lockscreen
Speeding Up Animations
Successfully Debloated Fire OS
Device Connected
```

**Comment by mrhaydendp** [comment]
After Fire OS 7.3.2.2 Amazon added a device administrator application that protects certain apps from being disabled, deleted, or cleared. This makes my Disable Ota and custom launcher not work, though most of the apps in the Debloat list disable just fine.

**Comment by dbolser** [comment]
Yeah, not terrible, but I wanted a 'clean' experience.

May try the lineage OS install
