### ISSUE TITLE
Launcher cannot be replaced (non-rooted)

### ISSUE THREAD

**Issue by galets** [mrhaydendp/Fire-Tools#41]
## Describe the Bug:

Tool can not replace launcher

## Steps to Reproduce:

- Start with brand new fire hd8 8th gen
- Amazon account not linked
- Run `./ui.sh`
- Choose "change launcher" option
- Choose "Nova"

Following is the output:

```
Device: Fire HD 8 (2018, 8th Gen)
Software: Fire OS 7.3.2.7 

Performing Streamed Install
Success
Security exception: Cannot disable a protected package: com.amazon.firelauncher

java.lang.SecurityException: Cannot disable a protected package: com.amazon.firelauncher
	at com.android.server.pm.PackageManagerService.setEnabledSetting(PackageManagerService.java:21114)
	at com.android.server.pm.PackageManagerService.setApplicationEnabledSetting(PackageManagerService.java:21025)
	at com.android.server.pm.PackageManagerShellCommand.runSetEnabledSetting(PackageManagerShellCommand.java:1617)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:208)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21671)
	at android.os.Binder.shellCommand(Binder.java:634)
	at android.os.Binder.onTransact(Binder.java:532)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2796)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3975)
	at android.os.Binder.execTransact(Binder.java:731)
Installed Launcher: com.teslacoilsw.launcher

```

Launcher stays as-is

## Expected Behavior:

Launcher is changed

## Platform:

Ubuntu 22.04

## Device:

- Fire HD 8 (2018, 8th Gen)
- Fire OS 7.3.2.7

**Comment by mrhaydendp** [comment]
Same as #40, Fire OS 7.3.2.2+ has a device administrator application that protects the stock launcher from being disabled or uninstalled. I'm working on integrating [Launcher Hijack](https://github.com/BaronKiko/LauncherHijack) into the tool if the disable method fails. Until then, you can install Launcher Hijack and select the launcher installed and it will remap the home button to your selected launcher.
